### ISSUE TITLE
Semana 1 - Trabajo realizado UO275955

### ISSUE THREAD

**Issue by lauracc97** [Arquisoft/wiq_es2a#26]
- Parte 1 (Sección de Requisitos), 3  y 7 de la documentación v0.1
- Forme parte de las decisiones grupales sobre el boceto del diseño de la app y de su arquitectura a seguir
- Búsqueda de información sobre la integración de MongoDB en la aplicación. He creado el cluster y enlazado con VSCode pero todavía no hemos conseguido integrarlo en la app. También he creado con ayuda de mis compañeros un prototipo base de la estructura con la que guardaremos los datos

**Comment by PLT2003** [comment]
Issues relevantes:
- Documentación parte 1: #12 
- Documentación parte 3: #14 
- Documentación parte 7: #18
- Prototipo: #8
- Creación BD: #24
