### ISSUE TITLE
Trabajo realizado por UO284247

### ISSUE THREAD

**Issue by yerayrdgzz** [Arquisoft/wiq_es2a#27]
- Parte 1 (Sección de stakeholders), 4 y 8 de la documentación v0.1.
- Investigación sobre posibles tecnologías útiles para la aplicación, comentadas entre todo el equipo para elegir la más conveniente.

**Comment by PLT2003** [comment]
Issues relevantes:
- Documentación parte 1: #12 
- Documentación parte 4: #15 
- Documentación parte 8: #19
